
import { LineEdit, Button } from "std-widgets.slint";

component CalculateButton {
    Button {
        text: "Calculate";
        primary: true; // primary color
        height: 35px;
    }
}

export component AppWindow inherits Window {
    background: #313e50;

    GridLayout {
        padding: 50px;
        spacing: 25px;

        Row {
            Text {
                text: "Enter Total Income";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
            }
        }
        Row {
            LineEdit {
                font-size: 16px;
                placeholder-text: "Enter a number";
                horizontal-alignment: center;
                height: 35px;
            }
        }
        Row {
            CalculateButton {}
        }
    }
}
