
import { LineEdit, Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    background: #313e50;

    in property <string> results: ""; // input public property (in)
    callback divide-income(string);

    GridLayout {
        padding: 50px;
        spacing: 25px;

        Row {
            Text {
                text: "Enter Total Income";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
            }
        }
        Row {
            income := LineEdit {
                font-size: 16px;
                placeholder-text: "Enter a number";
                horizontal-alignment: center;
                height: 35px;
            }
        }
        Row {
            Button {
                text: "Calculate";
                primary: true; // primary color
                height: 35px;
                clicked => { divide-income(income.text) }
            }
        }
        Row {
            VerticalBox {
                Rectangle {
                    height: 100px;
                    background: #f2f2f2;
                    Text {
                        color: black;
                        font-size: 16px;
                        font-weight: 500;
                        text: root.results;
                    }
                }
            }
        }
    }
}
